extern array_create
extern array_destroy
extern array_setup
extern array_size
extern array_get_count
extern array_append_item
extern array_item_exists
extern array_iterate

ARRAY_SIZE equ 12
BYTE_ARRAY_SIZE equ 12

extern byte_array_setup
extern byte_array_takedown
extern byte_array_append_null_terminated
extern byte_array_get_data_ptr_and_count
